# Generated by Django 4.2.6 on 2023-10-14 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judgehandle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laywers',
            fields=[
                ('laywer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateField()),
                ('bio', models.TextField()),
                ('specialization_area', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField()),
                ('end_schedule', models.DateTimeField()),
                ('Laywer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyerhandle.laywers')),
                ('appoinments_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='judgehandle.judgeappoinments')),
                ('judge_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='judgehandle.judges')),
            ],
        ),
    ]
