# Generated by Django 4.2.6 on 2023-10-14 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField()),
                ('crime_date', models.DateField()),
                ('state', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
                ('respondent', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=25)),
                ('sub_category', models.CharField(max_length=25)),
                ('police_station', models.CharField(max_length=25)),
                ('fir_number', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('court_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Respondents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('fir_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine1.ccb')),
            ],
        ),
        migrations.CreateModel(
            name='Petitioners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('fir_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine1.ccb')),
            ],
        ),
    ]
