# Generated by Django 4.2.6 on 2023-10-14 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judgehandle', '0001_initial'),
        ('lawyerhandle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('fir_id', models.AutoField(primary_key=True, serialize=False)),
                ('fir_number', models.CharField(max_length=20)),
                ('case_type', models.CharField(max_length=75)),
                ('priority', models.IntegerField()),
                ('sub_priority', models.FloatField()),
                ('emergency_tag', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Assigened',
            fields=[
                ('pre_id', models.AutoField(primary_key=True, serialize=False)),
                ('ccb_id', models.CharField(max_length=150)),
                ('priority', models.IntegerField()),
                ('judge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judgehandle.judges')),
                ('lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyerhandle.laywers')),
            ],
        ),
    ]
